import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// 加载Google Fonts的Inter字体
const inter = Inter({ subsets: ["latin"] });

// 设置网页的 meta 标签用于 SEO
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 导出 RootLayout 组件交给 Next 处理，接收任何类型的 React 子节点：children
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
